// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAW9dUO6aPPal37KKj2C7-suIDimGIwYls',
    appId: '1:428797584602:web:07f5b17085a1b87c1eb1e3',
    messagingSenderId: '428797584602',
    projectId: 'riffest-43f8d',
    authDomain: 'riffest-43f8d.firebaseapp.com',
    storageBucket: 'riffest-43f8d.appspot.com',
    measurementId: 'G-XTZ4HK2MQ0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADuMF_o1Ju8AbdITISuZ_YKVgvbPhaqfs',
    appId: '1:428797584602:android:0eee65f246b3d72e1eb1e3',
    messagingSenderId: '428797584602',
    projectId: 'riffest-43f8d',
    storageBucket: 'riffest-43f8d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtCWPubtgh9X2h-S9T5yEo1WGzdEIH3KU',
    appId: '1:428797584602:ios:51ac1d6a8c3ac3311eb1e3',
    messagingSenderId: '428797584602',
    projectId: 'riffest-43f8d',
    storageBucket: 'riffest-43f8d.appspot.com',
    iosBundleId: 'com.example.riffest',
  );

}